allowBuilds:
  '@parcel/watcher': true
  esbuild: true

engineStrict: true

shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1

catalogs:
  framework:
    nuxt: ^4.5.1
    pinia: ^4.0.2
    postcss-nested: ^8.0.0
    typescript: ^6.0.3
    vue: ^3.5.40
    vue-router: ^5.2.0
  quality:
    '@antfu/eslint-config': ^9.2.0
    '@zinkawaii/eslint-config-css': ^0.5.1
    eslint: ^10.8.0
  ui:
    '@iconify-json/ri': ^1.2.10
    '@nuxt/icon': ^2.4.1
    '@nuxt/image': ^2.1.0
    '@nuxtjs/color-mode': ^4.0.1
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
  util:
    '@nuxtjs/seo': ^5.3.6
    '@pinia/nuxt': ^1.0.1
    '@vueuse/core': ^14.4.0
    '@vueuse/nuxt': ^14.4.0
    fast-xml-parser: ^5.10.1
    temporal-polyfill: ^1.0.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
